### ISSUE TITLE
'NODE_OPTIONS' is not recognized as an internal or external command, an operable program, or a batch file.

### ISSUE THREAD

**Issue by denisprado** [payloadcms/payload-3.0-alpha-demo#27] opened 2024-03-10 15:36 UTC
Using Windows Powershell, I got this error when try to run npm run dev.

**Comment by DanRibbens** [comment] 2024-03-11 20:32
I am not able to reproduce this. When I run on windows it does as you would expect. Can you share the `dev` script in your own package.json?

If it has changed at all and you are trying to add `NODE_OPTIONS=...` then you will need to prefix it with `cross-env` to say `cross-env NODE_OPTIONS=...`

I'm closing this for now. If there is more info you can provide we can reopen it.

**Closed by DanRibbens** 2024-03-11 20:32 UTC

**Comment by denisprado** [comment] 2024-03-11 22:00
This is the script object:

 "scripts": {
    "dev": "NODE_OPTIONS=--no-deprecation next dev",
    "devsafe": "rm -rf .next && NODE_OPTIONS=--no-deprecation next dev",
    "build": "NODE_OPTIONS=--no-deprecation next build",
    "payload": "NODE_OPTIONS=--no-deprecation payload",
    "start": "NODE_OPTIONS=--no-deprecation next start",
    "lint": "NODE_OPTIONS=--no-deprecation next lint"
  },
  
and it is the original cloned from repo..

**Comment by denisprado** [comment] 2024-03-12 01:08
I am right, the problem is the peer dependencies.. with yarn the problem don't occur

**Comment by DanRibbens** [comment] 2024-03-12 01:56
Hey @denisprado,

Sorry for the confusion. When I looked at this issue I was not realizing that I had not pulled latest and you were right about the error. Thanks for reporting. If you pull again or copy the updated package.json to your project, it will run. This is the commit that addressed it: https://github.com/payloadcms/payload-3.0-alpha-demo/commit/92b5d9aad3395961cbf515146fbc1cd806368f5b
