### ISSUE TITLE
payload_preferences is not persisted for ListView/Collection table

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#29] opened 2024-03-11 00:13 UTC
When reordering columns from ListView on the `/admin/collections/user` page for example and then refreshing the page, or navigating away and coming back, those values are not persisted to preferences.

The first column is the place where you can click to navigate to a document. I've had scenarios where the first value wasn't required and for whatever reason the "default" view I have happens to be a blank field, which means that there is no way to navigate to that document via the UI. Even more troublesome is that if you reorder a different field to be in the first position, it does not update, effectively applying the anchor element to the new first column. It becomes even more annoying when you refresh the page, to find that the order is also not persisted, so there is essentially no way to access a document in some scenarios.

Overall, the columns feel like they could use a good looking at.

**Database adapter:** Postgres
**Package Manager:** pnpm
**Payload Alpha Version:** 41
**Node Version:** 18.19.0
Using `payload-3.0-alpha-demo` example ✅

**Comment by jacobsfletch** [comment] 2024-03-11 14:49
@HarleySalas so far unable to reproduce the list table preferences issue. When I change columns, a network request is fired off to update the preferences collection. Navigating around and refreshing persist the changes. Are you running locally, or browsing the public demo?

BUT I am able to reproduce the missing link issue. Reordering columns moves the link around and potentially makes is disappear altogether. This is a known issue (and wasn't always broken). I'll get this fixed today. Huge thank you for the bug reports.

**Comment by jacobsfletch** [comment] 2024-03-11 19:57
@HarleySalas I've got that last part fixed up in https://github.com/payloadcms/payload/pull/5295. It'll go out in the next alpha release. Still can't reproduce the preferences issue. Can you provide me with more concrete steps to reproduce? What does your network tab look like when you change columns?

**Comment by jacobsfletch** [comment] 2024-03-11 20:19
If the issue persists, feel free to provide some clear steps to reproduction. Closing until then. As always thank you for reporting on this 👍

**Closed by jacobsfletch** 2024-03-11 20:19 UTC

**Comment by HarleySalas** [comment] 2024-03-12 23:31
before even starting the server for the first time, I set `defaultColumns` in my `User` collection:
```
  admin: {
    useAsTitle: 'email',
    defaultColumns: ['email', 'roles', 'createdAt', 'updatedAt'],
  },
```
the first time I opened the User collection, I got it in the following  (incorrect) order:
`roles, updatedAt, createdAt, email`

refreshing the page after reordering manually, it reverted back to the incorrect order.

In network tab, I get a 200 response for `user-list` and when I see the values, they appear to be correct. 

When I refresh the page, I notice a post request for `user-list` again. Its physically changed it back to the wrong order, to the original (incorrect order); so that is a completely unintentional request that gets fired somehow, basically undoing my reorder.

The only changes I made from the v3 demo template are the following:

```
import { CollectionConfig } from 'payload/types'

export const User: CollectionConfig = {
  slug: 'user',
  auth: true,
  admin: {
    useAsTitle: 'email',
    defaultColumns: ['email', 'roles', 'createdAt', 'updatedAt'],
  },
  access: {},
  fields: [
    {
      name: 'roles',
      type: 'select',
      hasMany: true,
      defaultValue: ['user'],
      saveToJWT: true,
      options: [
        {
          label: 'User',
          value: 'user',
        },
        {
          label: 'Tenant',
          value: 'tenant',
        },
        {
          label: 'Admin',
          value: 'admin',
        },
      ],
    },
  ],
}
```

**Postgres** instead of mongo.

and `payload.config.ts`, where I include the `User.slug`

```
 admin: {
    user: User.slug,
  },
```


I have changed literally nothing else in the entire `alpha-demo`

using pnpm 8.15.4
all payload packages at alpha.48
node 18.19.0

**Comment by HarleySalas** [comment] 2024-03-12 23:52
It appears to only be happening with my `User` collection, so perhaps only `auth` enabled collections, or whatever collection is set as the `user` collection in the config's `admin.user`?
