### ISSUE TITLE
Using field type Select caues db error.

### ISSUE THREAD

**Issue by ThomasAunvik** [payloadcms/payload-3.0-alpha-demo#32] opened 2024-03-11 16:06 UTC
```
 ⨯ Internal error: error: column "backgroundColor" cannot be cast automatically to type enum_pages_blocks_textcontent_background_color
    at /home/thaun/Documents/Projects/payload-3.0-alpha-demo/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/home/thaun/Documents/Projects/payload-3.0-alpha-demo/node_modules/drizzle-kit/payload.js:34498:21)
    at async apply (/home/thaun/Documents/Projects/payload-3.0-alpha-demo/node_modules/drizzle-kit/payload.js:36648:9)
    at async pushDevSchema (./node_modules/@payloadcms/db-postgres/dist/utilities/pushDevSchema.js:47:5)
    at async Object.connect (./node_modules/@payloadcms/db-postgres/dist/connect.js:84:5)
    at async BasePayload.init (./node_modules/payload/dist/index.js:191:13)
```

```ts
import type { Field } from "payload/types";

const ColorSelect: Field = {
  name: "backgroundColor",
  type: "select",
  options: [
    {
      label: "Dark",
      value: "dark",
    },
    {
      label: "Dark Light",
      value: "dark_light",
    },
    {
      label: "Light",
      value: "light",
    },
    {
      label: "Gray",
      value: "gray",
    },
  ],
} as const;

export default ColorSelect;
```

Package.json:
```json
{
  "name": "next-latest-starter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "generate:types": "payload generate:types",
    "start": "next start",
    "lint": "next lint"
  },
  "engines": {
    "node": ">=18.17.0"
  },
  "dependencies": {
    "@payloadcms/db-mongodb": "3.0.0-alpha.44",
    "@payloadcms/db-postgres": "^3.0.0-alpha.44",
    "@payloadcms/next": "3.0.0-alpha.44",
    "@payloadcms/richtext-lexical": "3.0.0-alpha.44",
    "@payloadcms/richtext-slate": "3.0.0-alpha.44",
    "next": "14.2.0-canary.13",
    "payload": "3.0.0-alpha.44",
    "react": "^18",
    "react-dom": "^18",
    "sharp": "0.33.2"
  },
  "devDependencies": {
    "@biomejs/biome": "^1.6.0",
    "@swc/core": "^1.4.6",
    "@swc/register": "^0.1.10",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.4.18",
    "dotenv": "^16.4.5",
    "eslint": "^8",
    "eslint-config-next": "14.1.3",
    "postcss": "^8.4.35",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}
```

**Comment by paulpopus** [comment] 2024-03-11 18:47
Hey @ThomasAunvik I've just tested this exact field in postgres and mongo and I still cannot replicate it.

Are you seeing this on a fresh DB setup or? I'm wondering if it's potentially not related to 3.0 and a db schema issue?

**Comment by ThomasAunvik** [comment] 2024-03-11 23:35
I don't seem to get the same error on a fresh database no. Might be due to me reusing the same field names for different types.

First the field was a text field, now me turning it into a select. Gonna test it out a bit more.

**Comment by ThomasAunvik** [comment] 2024-03-12 07:55
Yeah it might seem that there are something wrong with the push migrations once i think.
Old db:
![old-db](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/9968151/9f611aab-36a4-4fd1-a96d-50ab1860903a)

New bd:
![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/9968151/e1f6e101-cea7-4ce7-ab95-aa741100946d)

**Comment by ThomasAunvik** [comment] 2024-03-12 11:44
Ok, i could show an example i think, i managed to reproduce it in a different manner too.

First add a field textarea, run the server, and a varchar column has been created.
```ts
{
  type: "textarea",
  name: "content",
},```

Now, edit to richText.
```ts
{
  type: "richText",
  name: "content",
}
```

Notice that you now get an error that it cannot convert the field into jsonb,
```
⨯ Internal error: error: column "content" cannot be cast automatically to type jsonb
    at /home/thaun/Documents/Projects/payload-3.0-alpha-demo/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/home/thaun/Documents/Projects/payload-3.0-alpha-demo/node_modules/drizzle-kit/payload.js:34498:21)
    at async apply (/home/thaun/Documents/Projects/payload-3.0-alpha-demo/node_modules/drizzle-kit/payload.js:36648:9)
    at async pushDevSchema (./node_modules/@payloadcms/db-postgres/dist/utilities/pushDevSchema.js:47:5)
    at async Object.connect (./node_modules/@payloadcms/db-postgres/dist/connect.js:84:5)
    at async BasePayload.init (./node_modules/payload/dist/index.js:191:13)
```

It might be a drizzle specific issue, but I am assuming it is failing to change the database type, or it just doesn't, but it should.

**Comment by paulpopus** [comment] 2024-03-12 16:11
Ok yeah I reproduced this, it's definitely a database schema thing and not v3 related. See: https://github.com/drizzle-team/drizzle-orm/issues/930

Gonna close this issue here since it's tracked upstream

**Closed by paulpopus** 2024-03-12 16:11 UTC
