### ISSUE TITLE
data and documentInfo are empty when using function to build URL in livePreview

### ISSUE THREAD

**Issue by rkgttr** [payloadcms/payload-3.0-alpha-demo#63] opened 2024-04-02 09:40 UTC
Hi,

First, thanks for your great work on Payload.

I try to dynamically build the url when using livePreview, into a collection, like this:
```
admin: {
    livePreview: {
      url: ({ data, documentInfo, locale }) => {
        console.log(data, documentInfo, locale)
        return `http://localhost:3000/${locale ? locale?.code : 'fr'}/${data.slug ? data.slug : ''}`
      },
    },
  },
```

And this doesn't work because `data `and `documentInfo `are empty; result of `console.log`:
`{} {} { label: { en: 'French', fr: 'Français' }, code: 'fr' }`

Thanks.

**Comment by jacobsfletch** [comment] 2024-04-03 14:41
Hey @rkgttr good catch, this is a known issue, the problem is that in 3.0, the url is determined on the server, where document info context doesn't exist. It's on our list of TODOs to get this figured out. We will either recreate the document info object server-side, or modify the args slightly based on what is available to us. `data` should still exist, however. I will look into both of these.

**Comment by jacobsfletch** [comment] 2024-04-05 17:02
@rkgttr I've got a fixed queued up for this in https://github.com/payloadcms/payload/pull/5692. I'll get that merged in, and it will go out in the next release. Thanks for the report on this 👍

**Closed** 2024-04-05 19:01 UTC
